name: Publish Nuget and Release
on: workflow_dispatch

jobs:

  nuget_release:

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.x

    - name: Pack
      run: dotnet pack
      working-directory: DevTools_lab01-Task-01\PowerCollections


    - name: Get XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with:
        xml-file: 'DevTools_lab01-Task-01/PowerCollections/PowerCollections/PowerCollections.csproj'
        xpath: '//version'
    - name: Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: 'DevTools_lab01-Task-01\PowerCollections\PowerCollections\bin\Debug\*${{ steps.getxml.outputs.info }}*.nupkg'
        tag: 'v${{ steps.getxml.outputs.info }}'
        version: 'v${{ steps.getxml.outputs.info }}'
